### ISSUE TITLE
可以不挂载ini文件而是挂载volume目录吗？

### ISSUE THREAD

**Issue by SuZixiong** [snowdreamtech/frp#20]
是否可以读取docker创建的volume中的ini文件，此volume目录已挂载到frp中。
```
version: "2.1"

services:
  frpc:
    restart: always
    network_mode: host
    volumes:
      - frpc_data:/frp

    container_name: frpc
    image: snowdreamtech/frpc


volumes:        
  frpc_data:
 
```

**Comment by SuZixiong** [comment]
改为如下挂载，成功读取了

```
version: "2.1"

services:
  frpc:
    restart: always
    network_mode: host
    volumes:
      - frpc_data:/etc/frp

    container_name: frpc
    image: snowdreamtech/frpc


volumes:        
  frpc_data:

```
