### ISSUE TITLE
应该使用CMD来传递frp参数, 而不是放在ENTRYPOINT里, 方便用户覆盖

### ISSUE THREAD

**Issue by KawaiiZapic** [snowdreamtech/frp#42]
按照现在的写法
```dockerfile
ENTRYPOINT /usr/bin/frpc -c /etc/frp/frpc.toml
```
在k8s中覆盖参数的话, 需要一同覆盖程序位置:
```yaml
containers:
    - command:
        - /usr/bin/frpc
        - '-c'
        - /etc/frp/frpc.yml
```
这样需要确定frpc的位置, 日后如果frpc位置更改就会破坏容器配置.  
如果使用CMD来传递参数:
```dockerfile
ENTRYPOINT /usr/bin/frpc
CMD -c /etc/frp/frpc.toml
```
可以不用关心frpc executable在哪, 直接覆写参数即可
```yaml
containers:
    - args:
        - '-c'
        - /etc/frp/frpc.yml
```
