### ISSUE TITLE
配置证书一直提示无法找到

### ISSUE THREAD

**Issue by Dev-Wiki** [snowdreamtech/frp#51]
客户端配置:
```yaml
version: "3"
services:
    frps:
        restart: always
        network_mode: host
        volumes:
            - /share/Docker/frpc-base/:/etc/frp/
            - /share/Docker/frpc-base/frpc.toml:/etc/frp/frpc.toml
        container_name: frpc-base
        image: snowdreamtech/frpc:0.57.0
```
无论是否删除 `- /share/Docker/frpc-base/:/etc/frp/` 均找不到

config：
```
[[proxies]]
name = "nas"
type = "https"
localIP = "127.0.0.1"
localPort = 5000
customDomains = ["nas.devwiki.net"]


[proxies.plugin]
type = "https2http"
localAddr = "127.0.0.1:5000"
# HTTPS 证书相关的配置
keyPath = "nas.devwiki.net.key"
crtPath = "nas.devwiki.net.crt"
hostHeaderRewrite = "nas.devwiki.net"
requestHeaders.set.x-from-where = "frp"
requestHeaders.set.x-forwarded-protol = "https"
requestHeaders.set.x-forwarded-port = "443"
```

运行结果：

frpc-base  | 2024-04-23 14:32:04.515 [W] [client/control.go:168] [aac6322f6d0276fa] [nas] start error: gen TLS config error: open nas.devwiki.net.crt: no such file or directory

![image](https://github.com/snowdreamtech/frp/assets/12946956/8d275165-7bea-460e-94a8-e8d3d2594272)
