### ISSUE TITLE
frps:0.58.1 无法使用配置

### ISSUE THREAD

**Issue by sliots** [snowdreamtech/frp#53]
> 2024-05-31 08:54:06.718 [I] [frps/root.go:107] frps uses command line arguments for config
2024-05-31 08:54:07.134 [I] [server/service.go:237] frps tcp listen on 0.0.0.0:7000
2024-05-31 08:54:07.134 [I] [frps/root.go:114] frps started successfully

docker-compose.yml
```
services:
  frps:
    image: snowdreamtech/frps:0.58.1

    container_name: frps
    restart: always
    network_mode: host
    volumes:
      - /mnt/docker/frp/frps.toml:/etc/frp/frps.toml
```

/mnt/docker/frp/frps.toml
```
bindPort = 12345
quicBindPort = 12345
auth.method = "token"
auth.token = "abcdefg"
```

**Comment by snowdream** [comment]
看看和这个有关系吗？

https://github.com/snowdreamtech/frp/issues/42

**Comment by okxlin** [comment]
+1 旧toml配置没法识别到，估计用了默认的

**Comment by okxlin** [comment]
确实启动命令和入口要修改，改了这样就正常了

![image](https://github.com/snowdreamtech/frp/assets/61420215/de6dee1a-31e7-4629-a813-7ebbf8f2b7d8)
```

services:
    frps:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: snowdreamtech/frps:latest
        labels:
            createdBy: Apps
        network_mode: host
        restart: always
        volumes:
            - ${CONFIG_FILE_PATH}:/etc/frp/frps.toml
            - ./data/ssl:/etc/frp/ssl
version: "3"

```
