### ISSUE TITLE
frps:0.58.1 无法使用配置

### ISSUE THREAD

**Issue by lw6644700** [snowdreamtech/frp#61]
最新的修复的还是不行啊，frpc是能启动，但是提示not supported when vhost http port is not set frp，退回0.58就可以，配置文件没有任何改动

**Comment by snowdream** [comment]
not supported when vhost http port is not set frp

**Comment by lw6644700** [comment]
> 未设置 FRP 的虚拟主机 HTTP 端口时不受支持
是啊，但是设置了啊，0.58就可以正常用，0.58.1配置文件不同了吗

**Comment by zhetc** [comment]
```yaml
version: "3"
services:
  frpc:
    image: snowdreamtech/frpc
    container_name: frpc
    network_mode: host
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /data/app/frp/frpc.toml:/etc/frp/frpc.toml
    command:
      - -c
      - /etc/frp/frpc.toml
```
docker-compose 可以参考这个，需要增加command这个参数，后面加上映射配置文件的路径
