### ISSUE TITLE
关于镜像时区的讨论

### ISSUE THREAD

**Issue by snowdream** [snowdreamtech/frp#63]
目前 apline 默认是采用 UTC 时间。

可以通过以下方法解决时区问题：

1. 在镜像内，安装 tzdata，然后设置时区
https://github.com/gliderlabs/docker-alpine/issues/136#issuecomment-341172222

```
FROM alpine:3.6
RUN apk add --no-cache tzdata
ENV TZ America/Los_Angeles
```

2. 挂载宿主机的时区：
把宿主机的时区
```
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
```
挂载到容器中去。

例如：
https://github.com/snowdreamtech/frp/issues/61#issuecomment-2143729098
```
version: "3"
services:
  frps:
    image: snowdreamtech/frps
    container_name: frps
    network_mode: host
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /data/app/frp/frps.toml:/etc/frp/frps.toml
      - /data/app/frp/404.html:/root/404.html
    command:
      - -c
      - /etc/frp/frps.toml

  frpc:
    image: snowdreamtech/frpc
    container_name: frpc
    network_mode: host
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /data/app/frp/frpc.toml:/etc/frp/frpc.toml
    command:
      - -c
      - /etc/frp/frpc.toml

```

第一种方法会增加镜像大小，并且需要提供环境变了 TZ，但是兼容性好。
第二种方法直接重复利用宿主机的时区，但是兼容性差一点。比如 Windows，就没有这些文件。
