### ISSUE TITLE
Mac 使用docker开启frpc注意事项

### ISSUE THREAD

**Issue by gexin1** [snowdreamtech/frp#86]
### Mac使用docker安装客户端注意
1. 个人使用的是snowdreamtech/frps 由于Mac 不支持
```shell
 --network host
```
所以我们无法在和宿主机器网络互通 
要手动打开端口
```yml
services:
  frpc:
    image: snowdreamtech/frpc:0.59
    container_name: frpc
    restart: always
    # network_mode: host #不支持
    ports:
      - "8080: 8080"
    volumes:
      - /path/to/frpc.toml:/etc/frp/frpc.toml
``` 
2.ssh服务22端口被占用 我们使用**host.docker.internal**来访问宿主机器
注意web地址服务要设置为**0.0.0.0**来接受所有地址的请求
```toml
webServer.addr = "0.0.0.0"
webServer.port = 8080
webServer.user = ""
webServer.password = ""

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "host.docker.internal"
localPort = 22
remotePort = 7000
```

### Affected area

- [X] Docs
